FROM ubuntu:16.04

# so that no question is asked during apt-get
ENV DEBIAN_FRONTEND noninteractive
# enable UTF-8 on terminal
ENV LANG en_US.UTF-8
# ensures xterm to support text-based UI tools, i.e. top, less, etc.
ENV TERM xterm

# Setup env:
RUN echo "export PS1='\e[1;31m\]\u@\h:\w\\$\[\e[0m\] '" >> /root/.bashrc

# Install basics:
RUN apt-get update && apt-get install -y \
    curl \
    git \
    locales \
    sudo \
    vim \
    wget && \
    rm -rf /var/lib/apt/lists/*

